# Generated by Django 5.2.5 on 2025-09-02 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=255, verbose_name="Ф.И.О.")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255, verbose_name="Тема письма")),
                ("body", models.TextField(verbose_name="Тело письма")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DateTimeField(verbose_name="Дата и время первой отправки")),
                ("end_time", models.DateTimeField(verbose_name="Дата и время окончания отправки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Создана"), ("Запущена", "Запущена"), ("Завершена", "Завершена")],
                        default="Создана",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("clients", models.ManyToManyField(to="mailing.client", verbose_name="Получатели")),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailing.message", verbose_name="Сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
